//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSales
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSales
    {
        public int ID { get; set; }
        public Nullable<double> SalesAmount { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
